language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
# to run PHPUnit on HHVM, you have to explicitly install version 5.7 in your .travis.yml due to a compatibility issue between HHVM and PHP7
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

# Commands you want to run that will verify your build.
script: phpunit Test.php

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 7.0
    - hhvm
    - nightly
  fast_finish: true

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - buluma:QWpyLHvuvJe5aduZtGs7euUa#travis-ci
  email:
    recipients:
      - me@buluma.me.ke
    on_success: always # default: change
    on_failure: always # default: always
