title: Ansible Roles
description: Simple and compatible Ansible roles for multi-distribution automation. Tested on Fedora, CentOS, Ubuntu, Debian, OpenSUSE, and more.
url: https://buluma.github.io
show_downloads: false
google_analytics: UA-39023378-1
repository: buluma/buluma.github.io
# theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
header: Ansible Roles

author:
  name: buluma
  email: buluma@example.com
  url: https://github.com/buluma

social:
  name: buluma
  links:
    - https://github.com/buluma

permalink: /:title/

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - node_modules/
